### ISSUE TITLE
routing config error on backend server

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#218]
@xcode75 I suddenly started to get this error message on (only two) of my backend servers from one hour ago:

May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: XMPlus v2.1.3 (A custom version of XrayR)
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: 2023/05/22 13:50:33 Starting XMPlus
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: 2023/05/22 13:50:33 Failed to understand Routing config  Please check: https://xtls.github.io/config/routing.html for help: infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ir-gov > infra/conf: failed to load geosite: CATEGORY-IR-GOV > infra/conf: list not found in geosite.dat: CATEGORY-IR-GOV
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: panic: Failed to understand Routing config  Please check: https://xtls.github.io/config/routing.html for help: infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ir-gov > infra/conf: failed to load geosite: CATEGORY-IR-GOV > infra/conf: list not found in geosite.dat: CATEGORY-IR-GOV
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: goroutine 1 [running]:
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: log.Panicf({0x31ca2fc?, 0x48a?}, {0xc000141be8?, 0x29ac160?, 0xc0004f6f50?})
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]:         log/log.go:391 +0x67
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: github.com/xcode75/XMPlus/panel.(*Panel).loadCore(0xc0005f3e68?, 0xc0001661c0)
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]:         github.com/xcode75/XMPlus/panel/panel.go:83 +0x3ff
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0004c9740)
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]:         github.com/xcode75/XMPlus/panel/panel.go:158 +0xe9
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]: main.main()
May 22 13:50:33 xm-backend-ch3 XMPlus[13630]:         github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
May 22 13:50:33 xm-backend-ch3 systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 22 13:50:33 xm-backend-ch3 systemd[1]: XMPlus.service: Failed with result 'exit-code'.
May 22 13:50:43 xm-backend-ch3 systemd[1]: XMPlus.service: Scheduled restart job, restart counter is at 23.
May 22 13:50:43 xm-backend-ch3 systemd[1]: Stopped XMPlus Service.
May 22 13:50:43 xm-backend-ch3 systemd[1]: Started XMPlus Service.

when I comment out routing in config.yml it keeps working fine. I did not change any thing whatsoever on any of my backend servers and frontend. The rest of the servers are working just fine. 

Here is the routing.json file I am using:

{
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "outboundTag": "blocked",
          "domain": [
            "regexp:.*\\.ir$",
            "ext:iran.dat:ir",
            "ext:iran.dat:other",
            "geosite:category-ir-gov",
            "geosite:category-ir-news",
            "geosite:category-ir-bank",
            "geosite:category-ir-tech",
            "geosite:category-ir-travel",
            "geosite:category-ir-shopping",
            "geosite:category-ir-insurance",
            "geosite:category-ir-scholar",
            "snapp", "digikala","tapsi", "blogfa", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org"
          ],
        "type": "field"
      }
    ]
}

I even deleted and reinstalled the backend from scratch but this happened again.

_Originally posted by @amihos in https://github.com/xcode75/XManagerPlus/issues/63#issuecomment-1557271683_

**Comment by amihos** [comment]
also noticed this :
![image](https://github.com/xcode75/XManagerPlus/assets/35190548/2b9e196c-0a4a-426d-b432-95deb0d19d01)
have no idea how did it happen. although as I stated before eventhough I reinstalled everything and now the file is back but still get the error:
![image](https://github.com/xcode75/XManagerPlus/assets/35190548/b7f81570-dfb6-4a5f-9327-1f8aeb6d8ac4)
