### ISSUE TITLE
[BUG] Error After Updating to v2.1.9 on Relay Node

### ISSUE THREAD

**Issue by amihos** [xcode75/XManagerPlus#331]
**Environment**
OS: CentOS 9
  
PHP version: 7.4.33
   
DB version: MySQL 5.7.43
  
Panel Version: XMPlus 1.0 - v20240718
    
Debug Info: Debug information not provided. Please enable debug in config.php and upload a screenshot.

**Bug Info**
After updating the backend from v2.1.4 to v2.1.9 (XMPlus v1) to match the new frontend (v20240718), an error occurs on a node with activated relay. The service starts but immediately crashes with a panic error related to VLESS user encryption settings.

Specific error message:
```
Jul 23 16:16:01 ubuntu XMPlus[74398]: panic: infra/conf: VLESS users: please add/set "encryption":"none" for every user
```

Full error log:
```
Jul 23 16:15:42 ubuntu systemd[1]: Started XMPlus Service.
Jul 23 16:15:42 ubuntu XMPlus[74368]: v2.1.9 - XMPlus v1
Jul 23 16:15:42 ubuntu XMPlus[74368]: 2024/07/23 16:15:42 [Debug] app/log: Logger started
Jul 23 16:15:42 ubuntu XMPlus[74368]: 2024/07/23 16:15:42 [Info] app/dns: DNS: created localhost client
Jul 23 16:15:42 ubuntu XMPlus[74368]: 2024/07/23 16:15:42 [Warning] core: Xray 1.8.21 started
Jul 23 16:15:43 ubuntu systemd[1]: Stopping XMPlus Service...
Jul 23 16:15:43 ubuntu systemd[1]: XMPlus.service: Deactivated successfully.
Jul 23 16:15:43 ubuntu systemd[1]: Stopped XMPlus Service.
Jul 23 16:15:43 ubuntu systemd[1]: Started XMPlus Service.
Jul 23 16:15:43 ubuntu XMPlus[74398]: v2.1.9 - XMPlus v1
Jul 23 16:15:43 ubuntu XMPlus[74398]: 2024/07/23 16:15:43 [Debug] app/log: Logger started
Jul 23 16:15:43 ubuntu XMPlus[74398]: 2024/07/23 16:15:43 [Info] app/dns: DNS: created localhost client
Jul 23 16:15:43 ubuntu XMPlus[74398]: 2024/07/23 16:15:43 [Warning] core: Xray 1.8.21 started
Jul 23 16:15:54 ubuntu XMPlus[74398]: 2024/07/23 16:15:54.190379 WARN RESTY Get "https://mydomain.com/api/v2/query/server/392?key=xxxxxxxx": net/http: TLS handshake timeout, Attempt 1
Jul 23 16:16:01 ubuntu XMPlus[74398]: 2024/07/23 16:16:01 infra/conf: VLESS users: please add/set "encryption":"none" for every user
Jul 23 16:16:01 ubuntu XMPlus[74398]: panic: infra/conf: VLESS users: please add/set "encryption":"none" for every user
Jul 23 16:16:01 ubuntu XMPlus[74398]: goroutine 1 [running]:
Jul 23 16:16:01 ubuntu XMPlus[74398]: log.Panic({0xc001d9fcd8?, 0xc001d46a80?, 0xc001d9fc98?})
Jul 23 16:16:01 ubuntu XMPlus[74398]:         log/log.go:432 +0x5a
Jul 23 16:16:01 ubuntu XMPlus[74398]: github.com/XMPlusDev/XMPlusv1/service/controller.(*Controller).Start(0xc00196f800)
Jul 23 16:16:01 ubuntu XMPlus[74398]:         github.com/XMPlusDev/XMPlusv1/service/controller/controller.go:103 +0x47b
Jul 23 16:16:01 ubuntu XMPlus[74398]: github.com/XMPlusDev/XMPlusv1/manager.(*Manager).Start(0xc00195a680)
Jul 23 16:16:01 ubuntu XMPlus[74398]:         github.com/XMPlusDev/XMPlusv1/manager/manager.go:190 +0x309
Jul 23 16:16:01 ubuntu XMPlus[74398]: main.main()
Jul 23 16:16:01 ubuntu XMPlus[74398]:         github.com/XMPlusDev/XMPlusv1/main/main.go:93 +0x299
Jul 23 16:16:01 ubuntu systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 23 16:16:01 ubuntu systemd[1]: XMPlus.service: Failed with result 'exit-code'.
Jul 23 16:16:11 ubuntu systemd[1]: XMPlus.service: Scheduled restart job, restart counter is at 1.
Jul 23 16:16:11 ubuntu systemd[1]: Stopped XMPlus Service.
```

The same node works perfectly fine with the previous backend version (v2.1.4):

```
Jul 23 16:20:33 ubuntu systemd[1]: Started XMPlus Service.
Jul 23 16:20:33 ubuntu XMPlus[76708]: XMPlus v2.1.4 (A custom version of XrayR for XMPlus v1.0)
Jul 23 16:20:33 ubuntu XMPlus[76708]: 2024/07/23 16:20:33 Starting XMPlus
Jul 23 16:20:33 ubuntu XMPlus[76708]: 2024/07/23 16:20:33 [Debug] app/log: Logger started
Jul 23 16:20:33 ubuntu XMPlus[76708]: 2024/07/23 16:20:33 [Info] app/dns: DNS: created localhost client
Jul 23 16:20:33 ubuntu XMPlus[76708]: 2024/07/23 16:20:33 [Warning] core: Xray 1.8.3 started
Jul 23 16:20:37 ubuntu XMPlus[76708]: 2024/07/23 16:20:37 [https://mydomain.com] Vless(NodeID=392) Taking a Detour Route [Relay_392_Vless_2053_394] For Users
Jul 23 16:20:37 ubuntu XMPlus[76708]: 2024/07/23 16:20:37 [https://mydomain.com] Vless(NodeID=392) 60 New Users Added
Jul 23 16:20:37 ubuntu XMPlus[76708]: 2024/07/23 16:20:37 [https://mydomain.com] Vless(NodeID=392) task scheduler for Node started
Jul 23 16:20:37 ubuntu XMPlus[76708]: 2024/07/23 16:20:37 [https://mydomain.com] Vless(NodeID=392) task scheduler for User started
Jul 23 16:20:37 ubuntu XMPlus[76708]: 2024/07/23 16:20:37 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:2053
Jul 23 16:20:37 ubuntu XMPlus[76708]: 2024/07/23 16:20:37 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:2053
```

Additional notes:
1. The error seems to be related to VLESS user encryption settings.
2. There's also a TLS handshake timeout error when trying to query the server.
3. The service attempts to restart but fails repeatedly.
4. There is something mentioned about xited, code=exited, status=2/INVALIDARGUMENT so I do not know if the way I need to setup the relay node is different in the new frontend or backend. 
I have seen this in the newer version of frontend which is called xmplus relay:
bash <(curl -Ls https://raw.githubusercontent.com/XMPlusDev/XMPlus-Relay/install/install.sh)
do I need to install this?

Steps to reproduce:
1. Update backend from v2.1.4 to v2.1.9 (XMPlus v1)
2. Update frontend to v20240718
3. Attempt to start the service on a node with activated relay

Expected behavior:
The service should start and run without errors, similar to the behavior observed with v2.1.4.

Actual behavior:
The service starts but immediately crashes with a panic error related to VLESS user encryption settings.

Possible solution:
The error message suggests adding or setting "encryption":"none" for every VLESS user. This might be a configuration change required in the new version.

Here is how i setup this node:
![image](https://github.com/user-attachments/assets/88243146-90f7-45c9-9285-07865dcc367a)

![image](https://github.com/user-attachments/assets/58b1ab19-933a-46fe-bd03-f206b305a487)

![image](https://github.com/user-attachments/assets/8f09bf3d-14cb-41b9-878f-624b16943c0f)

**Comment by xcode75** [comment]
noted
